services:
  mongo:
    build: ./docker/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:root@mongo:27017
    volumes:
      - node_modules:/app/node_modules

volumes:
  mongo_data:
  node_modules:
